In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn

# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt


from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical 

C:\Users\thewa\anaconda3\lib\site-packages\requests\__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (2.0.3)/charset_normalizer (2.0.4) doesn't match a supported version!
  warnings.warn(


In [2]:
df = pd.read_csv('diabetes.csv') 
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [4]:
X = df.drop('Outcome',axis = 1) #independent 

In [5]:
y = df['Outcome'] #dependent 

In [6]:
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [7]:
X = X.values #dataframe into its respective array format

In [8]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [10]:
y = df['Outcome']



In [11]:
y = y.values

In [12]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [13]:
X_train, X_test, y_trai,n y_test = train_test_split(X, y, test_size=0.30, random_state=40)
print(X_train.shape); print(X_test.shape)

(537, 8)
(231, 8)


In [16]:
y_train[0:5]

array([1, 1, 1, 0, 0], dtype=int64)

In [18]:
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

count_classes = y_test.shape[1]
print(count_classes)

2


In [19]:
y_train[0:5]

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [20]:
model = Sequential()
model.add(Dense(500, activation='relu', input_dim=8))
model.add(Dense(100, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(2, activation='softmax'))

# Compile the model
model.compile(optimizer='adam', 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])

In [21]:
model.fit(X_train, y_train, epochs=200)


Epoch 1/200
17/17 [==============================] - 1s 2ms/step - loss: 2.2346 - accuracy: 0.5456
Epoch 2/200
17/17 [==============================] - 0s 3ms/step - loss: 0.6688 - accuracy: 0.6946
Epoch 3/200
17/17 [==============================] - 0s 2ms/step - loss: 0.6081 - accuracy: 0.6946
Epoch 4/200
17/17 [==============================] - 0s 4ms/step - loss: 0.6265 - accuracy: 0.6760
Epoch 5/200
17/17 [==============================] - 0s 4ms/step - loss: 0.6589 - accuracy: 0.6648
Epoch 6/200
17/17 [==============================] - 0s 3ms/step - loss: 0.5882 - accuracy: 0.6946
Epoch 7/200
17/17 [==============================] - 0s 4ms/step - loss: 0.5698 - accuracy: 0.7095
Epoch 8/200
17/17 [==============================] - 0s 3ms/step - loss: 0.5956 - accuracy: 0.6983
Epoch 9/200
17/17 [==============================] - 0s 3ms/step - loss: 0.5735 - accuracy: 0.6983
Epoch 10/200
17/17 [==============================] - 0s 3ms/step - loss: 0.6381 - accuracy: 0.6890
Epoch 11/

17/17 [==============================] - 0s 3ms/step - loss: 0.4623 - accuracy: 0.7765
Epoch 83/200
17/17 [==============================] - 0s 4ms/step - loss: 0.4484 - accuracy: 0.7821
Epoch 84/200
17/17 [==============================] - 0s 4ms/step - loss: 0.4505 - accuracy: 0.7989
Epoch 85/200
17/17 [==============================] - 0s 6ms/step - loss: 0.4316 - accuracy: 0.8063
Epoch 86/200
17/17 [==============================] - 0s 9ms/step - loss: 0.4386 - accuracy: 0.7821
Epoch 87/200
17/17 [==============================] - 0s 4ms/step - loss: 0.4149 - accuracy: 0.8026
Epoch 88/200
17/17 [==============================] - 0s 3ms/step - loss: 0.4236 - accuracy: 0.8045
Epoch 89/200
17/17 [==============================] - 0s 3ms/step - loss: 0.4176 - accuracy: 0.7933
Epoch 90/200
17/17 [==============================] - 0s 3ms/step - loss: 0.4237 - accuracy: 0.7840
Epoch 91/200
17/17 [==============================] - 0s 3ms/step - loss: 0.4424 - accuracy: 0.7970
Epoch 92/200


17/17 [==============================] - 0s 4ms/step - loss: 0.3659 - accuracy: 0.8343
Epoch 164/200
17/17 [==============================] - 0s 7ms/step - loss: 0.3499 - accuracy: 0.8436
Epoch 165/200
17/17 [==============================] - 0s 5ms/step - loss: 0.3497 - accuracy: 0.8250
Epoch 166/200
17/17 [==============================] - 0s 5ms/step - loss: 0.3288 - accuracy: 0.8324
Epoch 167/200
17/17 [==============================] - 0s 3ms/step - loss: 0.3316 - accuracy: 0.8603
Epoch 168/200
17/17 [==============================] - 0s 3ms/step - loss: 0.3156 - accuracy: 0.8287
Epoch 169/200
17/17 [==============================] - 0s 4ms/step - loss: 0.3223 - accuracy: 0.8492
Epoch 170/200
17/17 [==============================] - 0s 5ms/step - loss: 0.3292 - accuracy: 0.8287
Epoch 171/200
17/17 [==============================] - 0s 4ms/step - loss: 0.3018 - accuracy: 0.8696
Epoch 172/200
17/17 [==============================] - 0s 3ms/step - loss: 0.3050 - accuracy: 0.8510
Epoc

In [32]:
from sklearn.metrics import f1_score
training_data_pred = model.predict(X_train) #class test
scores = model.evaluate(X_train, y_train, verbose=1) #x_train


17/17 [==============================] - 0s 3ms/step - loss: 0.3141 - accuracy: 0.8547


In [24]:
scores

[0.3141210973262787, 0.8547486066818237]

In [25]:
print(f"training accuracy is {scores[1]}")

training accuracy is 0.8547486066818237


In [26]:
print(f"training error is {1 - scores[1]}")

training error is 0.14525139331817627


In [27]:
pred_test= model.predict(X_test) #final_test


In [28]:
scores2 = model.evaluate(X_test, y_test, verbose=0)


In [29]:
print(f"test accuracy is {scores2[1]}")

test accuracy is 0.6623376607894897


In [30]:
print(f"test error is {1 - scores2[1]}")

test error is 0.33766233921051025
